### ISSUE TITLE
Cannot get FULL URLs including request parameters?

### ISSUE THREAD

**Issue by osmszk** [ubapsi/appchk-app#2]
Thank you for publishing extremely amazing codes.

I have a question.
I confirmed to get URL hosts that the device is requesting by local VPN.
Like this. below image: `completion.amazon.co.jp`, `fls-fe.amazon.co.jp`, `unagi.amazon.co.jp`, `www.amazon.co.jp`

But I want to get FULL URL  but not only host.
Like this: `https://www.amazon.co.jp/dp/B08YRKYLR9/ref=cm_sw_r_tw_dp_JB9A1VEQ20340DVBAM1X?_encoding=UTF8&psc=1`
Can I get Full URLs including request parameters? If yes, could you show me how to?
Thank you.

### Hosts sample
<img src="https://user-images.githubusercontent.com/703647/121754277-27789180-cb4f-11eb-9687-83d59f17e65f.jpg" width="40%">

**Comment by ghost** [comment]
Hi, this could turn out to be quite tricky. Here is the code that gets written to the database. NEKit exposes the domain name only (`session.host`). Most likely you will need to look inside the network packets which, probably, will require TLS interception. I am not 100% sure at which point the Proxy Socket intercepts network requests and whether it does actually require TLS interception or not. Anyway, you can start by adding a new case `.wroteData(data, on: socket)` and see whats inside the `data` param. At least on http connections you should see the ressource path aka full URL.

https://github.com/UBA-PSI/appchk-app/blob/b195daf1242a9eb4f19710ca8df01ccd3292e815/GlassVPN/PacketTunnelProvider.swift#L19-L31

**Comment by osmszk** [comment]
Thank you for your reply. 
In case of HTTP connection, I got the resource path (full URL)   by adding `readData(data, on: socket)`, thanks to your comment.
But I could not get it on TLS connection. In case of TLS(SSL), I could read only Header (such as `CONNECT www.amazon.co.jp:443 HTTP/1.1 ... `). 
I think it is impossible to read any full resource path on TLS packet... unless I set up a HTTPS proxy server on iOS apps using a self-signed certificate :(.   Do you know whether or not Apple allows developers to do this? I know we can intercept using `Content Filter` extension  for supervised devices.  Because I want to use `Packet Tunnel` extension, there is no choice to use `Content Filter`.

And, 
do you have any ideas to intercept TLS packets and read resource paths?
Thank you.

**Comment by ghost** [comment]
I am pretty sure that such an app can be admitted to the AppStore. In fact, another app, [Charles for iOS][1], does exactly that and is available on the AppStore. Depending on your use-case, maybe using Charles is sufficient for you?

As for TLS interception, I have no idea where to start. As you said, you would need to create a self-signed certificate and deliver that to an app instead of the original certificate. Plus, you will run into problems with high-security apps like banking apps for example. These apps will most likely pin their certificate to the app and simply won't work with your own certificate.

[1]: https://www.charlesproxy.com/documentation/ios/

**Comment by osmszk** [comment]
Thank you for your kindness!
I will keep researching this theme, and install Charles for iOS! (Thanks! nice info!)
